const enISOData = [
  { Name: "Afghanistan", Value: "AF" },
  { Name: "Åland Islands", Value: "AX" },
  { Name: "Albania", Value: "AL" },
  { Name: "Algeria", Value: "DZ" },
  { Name: "American Samoa", Value: "AS" },
  { Name: "Andorra", Value: "AD" },
  { Name: "Angola", Value: "AO" },
  { Name: "Anguilla", Value: "AI" },
  { Name: "Antarctica", Value: "AQ" },
  { Name: "Antigua and Barbuda", Value: "AG" },
  { Name: "Argentina", Value: "AR" },
  { Name: "Armenia", Value: "AM" },
  { Name: "Aruba", Value: "AW" },
  { Name: "Australia", Value: "AU" },
  { Name: "Austria", Value: "AT" },
  { Name: "Azerbaijan", Value: "AZ" },
  { Name: "Bahamas", Value: "BS" },
  { Name: "Bahrain", Value: "BH" },
  { Name: "Bangladesh", Value: "BD" },
  { Name: "Barbados", Value: "BB" },
  { Name: "Belarus", Value: "BY" },
  { Name: "Belgium", Value: "BE" },
  { Name: "Belize", Value: "BZ" },
  { Name: "Benin", Value: "BJ" },
  { Name: "Bermuda", Value: "BM" },
  { Name: "Bhutan", Value: "BT" },
  { Name: "Bolivia", Value: "BO" },
  { Name: "Bonaire", Value: "BQ" },
  { Name: "Bosnia and Herzegovina", Value: "BA" },
  { Name: "Botswana", Value: "BW" },
  { Name: "Bouvet Island", Value: "BV" },
  { Name: "Brazil", Value: "BR" },
  { Name: "British Indian Ocean Territory", Value: "IO" },
  { Name: "British Virgin Islands", Value: "VG" },
  { Name: "Brunei", Value: "BN" },
  { Name: "Bulgaria", Value: "BG" },
  { Name: "Burkina Faso", Value: "BF" },
  { Name: "Burundi", Value: "BI" },
  { Name: "Cabo Verde", Value: "CV" },
  { Name: "Cambodia", Value: "KH" },
  { Name: "Cameroon", Value: "CM" },
  { Name: "Canada", Value: "CA" },
  { Name: "Cayman Islands", Value: "KY" },
  { Name: "Central African Republic", Value: "CF" },
  { Name: "Chad", Value: "TD" },
  { Name: "Chile", Value: "CL" },
  { Name: "China", Value: "CN" },
  { Name: "Christmas Island", Value: "CX" },
  { Name: "Cocos (Keeling) Islands", Value: "CC" },
  { Name: "Colombia", Value: "CO" },
  { Name: "Comoros", Value: "KM" },
  { Name: "Congo", Value: "CG" },
  { Name: "Congo (DRC)", Value: "CD" },
  { Name: "Cook Islands", Value: "CK" },
  { Name: "Costa Rica", Value: "CR" },
  { Name: "Côte d’Ivoire", Value: "CI" },
  { Name: "Croatia", Value: "HR" },
  { Name: "Cuba", Value: "CU" },
  { Name: "Curaçao", Value: "CW" },
  { Name: "Cyprus", Value: "CY" },
  { Name: "Czechia", Value: "CZ" },
  { Name: "Denmark", Value: "DK" },
  { Name: "Djibouti", Value: "DJ" },
  { Name: "Dominica", Value: "DM" },
  { Name: "Dominican Republic", Value: "DO" },
  { Name: "Ecuador", Value: "EC" },
  { Name: "Egypt", Value: "EG" },
  { Name: "El Salvador", Value: "SV" },
  { Name: "Equatorial Guinea", Value: "GQ" },
  { Name: "Eritrea", Value: "ER" },
  { Name: "Estonia", Value: "EE" },
  { Name: "Eswatini", Value: "SZ" },
  { Name: "Ethiopia", Value: "ET" },
  { Name: "Falkland Islands", Value: "FK" },
  { Name: "Faroe Islands", Value: "FO" },
  { Name: "Fiji", Value: "FJ" },
  { Name: "Finland", Value: "FI" },
  { Name: "France", Value: "FR" },
  { Name: "French Guiana", Value: "GF" },
  { Name: "French Polynesia", Value: "PF" },
  { Name: "French Southern Territories", Value: "TF" },
  { Name: "Gabon", Value: "GA" },
  { Name: "Gambia", Value: "GM" },
  { Name: "Georgia", Value: "GE" },
  { Name: "Germany", Value: "DE" },
  { Name: "Ghana", Value: "GH" },
  { Name: "Gibraltar", Value: "GI" },
  { Name: "Greece", Value: "GR" },
  { Name: "Greenland", Value: "GL" },
  { Name: "Grenada", Value: "GD" },
  { Name: "Guadeloupe", Value: "GP" },
  { Name: "Guam", Value: "GU" },
  { Name: "Guatemala", Value: "GT" },
  { Name: "Guernsey", Value: "GG" },
  { Name: "Guinea", Value: "GN" },
  { Name: "Guinea-Bissau", Value: "GW" },
  { Name: "Guyana", Value: "GY" },
  { Name: "Haiti", Value: "HT" },
  { Name: "Heard Island and McDonald Islands", Value: "HM" },
  { Name: "Honduras", Value: "HN" },
  { Name: "Hong Kong SAR", Value: "HK" },
  { Name: "Hungary", Value: "HU" },
  { Name: "Iceland", Value: "IS" },
  { Name: "India", Value: "IN" },
  { Name: "Indonesia", Value: "ID" },
  { Name: "Iran", Value: "IR" },
  { Name: "Iraq", Value: "IQ" },
  { Name: "Ireland", Value: "IE" },
  { Name: "Isle of Man", Value: "IM" },
  { Name: "Israel", Value: "IL" },
  { Name: "Italy", Value: "IT" },
  { Name: "Jamaica", Value: "JM" },
  { Name: "Japan", Value: "JP" },
  { Name: "Jersey", Value: "JE" },
  { Name: "Jordan", Value: "JO" },
  { Name: "Kazakhstan", Value: "KZ" },
  { Name: "Kenya", Value: "KE" },
  { Name: "Kiribati", Value: "KI" },
  { Name: "Korea", Value: "KR" },
  { Name: "Kosovo", Value: "XK" },
  { Name: "Kuwait", Value: "KW" },
  { Name: "Kyrgyzstan", Value: "KG" },
  { Name: "Laos", Value: "LA" },
  { Name: "Latvia", Value: "LV" },
  { Name: "Lebanon", Value: "LB" },
  { Name: "Lesotho", Value: "LS" },
  { Name: "Liberia", Value: "LR" },
  { Name: "Libya", Value: "LY" },
  { Name: "Liechtenstein", Value: "LI" },
  { Name: "Lithuania", Value: "LT" },
  { Name: "Luxembourg", Value: "LU" },
  { Name: "Macao SAR", Value: "MO" },
  { Name: "Madagascar", Value: "MG" },
  { Name: "Malawi", Value: "MW" },
  { Name: "Malaysia", Value: "MY" },
  { Name: "Maldives", Value: "MV" },
  { Name: "Mali", Value: "ML" },
  { Name: "Malta", Value: "MT" },
  { Name: "Marshall Islands", Value: "MH" },
  { Name: "Martinique", Value: "MQ" },
  { Name: "Mauritania", Value: "MR" },
  { Name: "Mauritius", Value: "MU" },
  { Name: "Mayotte", Value: "YT" },
  { Name: "Mexico", Value: "MX" },
  { Name: "Micronesia", Value: "FM" },
  { Name: "Moldova", Value: "MD" },
  { Name: "Monaco", Value: "MC" },
  { Name: "Mongolia", Value: "MN" },
  { Name: "Montenegro", Value: "ME" },
  { Name: "Montserrat", Value: "MS" },
  { Name: "Morocco", Value: "MA" },
  { Name: "Mozambique", Value: "MZ" },
  { Name: "Myanmar", Value: "MM" },
  { Name: "Namibia", Value: "NA" },
  { Name: "Nauru", Value: "NR" },
  { Name: "Nepal", Value: "NP" },
  { Name: "Netherlands", Value: "NL" },
  { Name: "New Caledonia", Value: "NC" },
  { Name: "New Zealand", Value: "NZ" },
  { Name: "Nicaragua", Value: "NI" },
  { Name: "Niger", Value: "NE" },
  { Name: "Nigeria", Value: "NG" },
  { Name: "Niue", Value: "NU" },
  { Name: "Norfolk Island", Value: "NF" },
  { Name: "North Korea", Value: "KP" },
  { Name: "North Macedonia", Value: "MK" },
  { Name: "Northern Mariana Islands", Value: "MP" },
  { Name: "Norway", Value: "NO" },
  { Name: "Oman", Value: "OM" },
  { Name: "Pakistan", Value: "PK" },
  { Name: "Palau", Value: "PW" },
  { Name: "Palestinian Authority", Value: "PS" },
  { Name: "Panama", Value: "PA" },
  { Name: "Papua New Guinea", Value: "PG" },
  { Name: "Paraguay", Value: "PY" },
  { Name: "Peru", Value: "PE" },
  { Name: "Philippines", Value: "PH" },
  { Name: "Pitcairn Islands", Value: "PN" },
  { Name: "Poland", Value: "PL" },
  { Name: "Portugal", Value: "PT" },
  { Name: "Puerto Rico", Value: "PR" },
  { Name: "Qatar", Value: "QA" },
  { Name: "Réunion", Value: "RE" },
  { Name: "Romania", Value: "RO" },
  { Name: "Russia", Value: "RU" },
  { Name: "Rwanda", Value: "RW" },
  { Name: "Saba", Value: "BQ" },
  { Name: "Saint Barthélemy", Value: "BL" },
  { Name: "Saint Kitts and Nevis", Value: "KN" },
  { Name: "Saint Lucia", Value: "LC" },
  { Name: "Saint Martin", Value: "MF" },
  { Name: "Saint Pierre and Miquelon", Value: "PM" },
  { Name: "Saint Vincent and the Grenadines", Value: "VC" },
  { Name: "Samoa", Value: "WS" },
  { Name: "San Marino", Value: "SM" },
  { Name: "São Tomé and Príncipe", Value: "ST" },
  { Name: "Saudi Arabia", Value: "SA" },
  { Name: "Senegal", Value: "SN" },
  { Name: "Serbia", Value: "RS" },
  { Name: "Seychelles", Value: "SC" },
  { Name: "Sierra Leone", Value: "SL" },
  { Name: "Singapore", Value: "SG" },
  { Name: "Sint Maarten", Value: "SX" },
  { Name: "Slovakia", Value: "SK" },
  { Name: "Slovenia", Value: "SI" },
  { Name: "Solomon Islands", Value: "SB" },
  { Name: "Somalia", Value: "SO" },
  { Name: "South Africa", Value: "ZA" },
  {
    Name: "South Georgia and South Sandwich Islands",
    Value: "GS",
  },
  { Name: "South Sudan", Value: "SS" },
  { Name: "Spain", Value: "ES" },
  { Name: "Sri Lanka", Value: "LK" },
  {
    Name: "St Helena, Ascension, Tristan da Cunha",
    Value: "SH",
  },
  { Name: "Sudan", Value: "SD" },
  { Name: "Suriname", Value: "SR" },
  { Name: "Svalbard", Value: "SJ" },
  { Name: "Sweden", Value: "SE" },
  { Name: "Switzerland", Value: "CH" },
  { Name: "Syria", Value: "SY" },
  { Name: "Taiwan", Value: "TW" },
  { Name: "Tajikistan", Value: "TJ" },
  { Name: "Tanzania", Value: "TZ" },
  { Name: "Thailand", Value: "TH" },
  { Name: "Timor-Leste", Value: "TL" },
  { Name: "Togo", Value: "TG" },
  { Name: "Tokelau", Value: "TK" },
  { Name: "Tonga", Value: "TO" },
  { Name: "Trinidad and Tobago", Value: "TT" },
  { Name: "Tunisia", Value: "TN" },
  { Name: "Turkey", Value: "TR" },
  { Name: "Turkmenistan", Value: "TM" },
  { Name: "Turks and Caicos Islands", Value: "TC" },
  { Name: "Tuvalu", Value: "TV" },
  { Name: "U.S. Outlying Islands", Value: "UM" },
  { Name: "U.S. Virgin Islands", Value: "VI" },
  { Name: "Uganda", Value: "UG" },
  { Name: "Ukraine", Value: "UA" },
  { Name: "United Arab Emirates", Value: "AE" },
  { Name: "United Kingdom", Value: "GB" },
  { Name: "United States", Value: "US" },
  { Name: "Uruguay", Value: "UY" },
  { Name: "Uzbekistan", Value: "UZ" },
  { Name: "Vanuatu", Value: "VU" },
  { Name: "Vatican City", Value: "VA" },
  { Name: "Venezuela", Value: "VE" },
  { Name: "Vietnam", Value: "VN" },
  { Name: "Wallis and Futuna", Value: "WF" },
  { Name: "Yemen", Value: "YE" },
  { Name: "Zambia", Value: "ZM" },
  { Name: "Zimbabwe", Value: "ZW" },
];

module.exports = enISOData;
